name: Deploy

on:
  push:
    branches:
      - main

  workflow_dispatch:
  repository_dispatch:
    types: [svg-docs-updated]

permissions:
  contents: read

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  svg-docs:
    uses: /.github/workflows/svg-docs.yml

  build:
    needs: svg-docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v7.0.0
        with:
          node-version: 24
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Download SVG Docs
        uses: actions/download-artifact@v5
        with:
          name: svg-docs
          path: pages

      - name: Build site
        run: yarn build

      - name: Configure Pages
        uses: actions/configure-pages@v6

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: dist

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v5